from tkinter import *
root=Tk()
root.geometry("500x550")
root.minsize(500,550)
root.maxsize(500,550)
root.wm_iconbitmap("1.ico")
root.title("Calculator by Mansoor")
root.config(bg="midnightblue")
root.resizable(0,0)

def click(event):
    text=event.widget.cget("text")
    if text=="=":
        try:
            text = eval(str(scval.get()))
        except Exception as e:
            text="ERROR !!!"

        scval.set(text)
        text=""
    elif text=="C":
        scval.set("")
    else:
        scval.set(scval.get()+text)

scval=StringVar()
Label(root,text="Simple Calculator",font="georgia 21 bold",fg="pink1",bg="midnightblue").pack(fill=X,side=TOP)
e=Entry(root,textvar=scval,font="lucida 25 bold",justify=RIGHT)
e.pack(fill=X,ipadx=100,ipady=1,pady=6,padx=6)
f1=Frame(root,bg="skyblue4")
f1.pack()
b=Button(f1,text="9",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
b=Button(f1,text="8",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
b=Button(f1,text="7",font="lucida 20 bold",width=3,padx=10,pady=10)
b.pack(side=LEFT,padx=10,pady=10)
b.bind("<Button-1>",click)
b=Button(f1,text="+",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
# ----------------------------------------------------------------------------
f1=Frame(root,bg="skyblue4")
f1.pack()
b=Button(f1,text="4",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
b=Button(f1,text="5",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
b=Button(f1,text="6",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
b=Button(f1,text="-",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
# --------------------------------------------------------------------------
f1=Frame(root,bg="skyblue4")
f1.pack()
b=Button(f1,text="1",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
b=Button(f1,text="2",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
b=Button(f1,text="3",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
b=Button(f1,text="*",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
# ------------------------------------------------------------------------------
f1=Frame(root,bg="skyblue4")
f1.pack()
b.pack(side=LEFT,padx=10,pady=10)
b=Button(f1,text="C",font="lucida 20 bold",width=8,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10,ipadx=7)
b=Button(f1,text="0",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
b=Button(f1,text="/",font="lucida 20 bold",width=3,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10)
f1=Frame(root,bg="skyblue4")
f1.pack()
b=Button(f1,text="=",font="lucida 20 bold",width=20,padx=10,pady=10)
b.bind("<Button-1>",click)
b.pack(side=LEFT,padx=10,pady=10,ipadx=4)

root.mainloop()